### ISSUE TITLE
Dynamic-sidecar: cannot stop and fails uploading with Permission denied

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#6306]
Some symlinks in a Jupyterlab makes the whole service fail to close/upload resulting in data loss.

Do the following:
- start a Jupyter Math
- enter a Terminal
- run
```bash
pip install uv
uv venv --python 3.12
source .venv/bin/activate
uv pip install numpy pandas distributed couch
```
- now go back to the dashboard
--> the study never closes, well it appears to close after a long while, re-opening it results in a failure
--> data loss???

Some logs of the dynamic sidecar:
```
log_level=WARNING | log_timestamp=2024-09-04 18:19:29,278 | log_source=servicelib.utils:logged_gather(142) | log_uid=None | log_msg=Error in 1-th concurrent task <coroutine object _save_state_folder at 0x78b45e0bdbc0>: [Errno 13] Permission denied: '/dy-volumes/home/jovyan/work/workspace/.venv/bin/python.rclonelink'

log_level=WARNING | log_timestamp=2024-09-04 18:19:29,656 | log_source=servicelib.long_running_tasks.task:get_task_result_old(263) | log_uid=None | log_msg=Task simcore_service_dynamic_sidecar.modules.long_running_tasks.task_save_state.703c6626-9fd1-449d-8099-85f9c55880b0 finished with error: Task simcore_service_dynamic_sidecar.modules.long_running_tasks.task_save_state.703c6626-9fd1-449d-8099-85f9c55880b0 finished with exception: '[Errno 13] Permission denied: '/dy-volumes/home/jovyan/work/workspace/.venv/bin/python.rclonelink''
  File "/home/scu/.venv/lib/python3.11/site-packages/servicelib/long_running_tasks/task.py", line 422, in _progress_task
    return await handler(progress, **task_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/scu/.venv/lib/python3.11/site-packages/simcore_service_dynamic_sidecar/modules/long_running_tasks.py", line 440, in task_save_state
    await logged_gather(

  File "/home/scu/.venv/lib/python3.11/site-packages/servicelib/utils.py", line 154, in logged_gather
    raise error

  File "/home/scu/.venv/lib/python3.11/site-packages/servicelib/utils.py", line 131, in sem_task
    return await task
           ^^^^^^^^^^

  File "/home/scu/.venv/lib/python3.11/site-packages/simcore_service_dynamic_sidecar/modules/long_running_tasks.py", line 403, in _save_state_folder
    await data_manager.push(

  File "/home/scu/.venv/lib/python3.11/site-packages/simcore_sdk/node_data/data_manager.py", line 208, in push
    await _push_directory(

  File "/home/scu/.venv/lib/python3.11/site-packages/simcore_sdk/node_data/data_manager.py", line 51, in _push_directory
    await filemanager.upload_path(

  File "/home/scu/.venv/lib/python3.11/site-packages/simcore_sdk/node_ports_common/filemanager.py", line 313, in upload_path
    async for attempt in AsyncRetrying(

  File "/home/scu/.venv/lib/python3.11/site-packages/tenacity/asyncio/__init.py", line 166, in anext
    do = await self.iter(retry_state=self.retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/scu/.venv/lib/python3.11/site-packages/tenacity/asyncio/_init.py", line 153, in iter
    result = await action(retry_state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/scu/.venv/lib/python3.11/site-packages/tenacity/utils.py", line 99, in inner
    return call(args, *kwargs)
           ^^^^^^^^^^^^^^^^^^^^^

  File "/home/scu/.venv/lib/python3.11/site-packages/tenacity/_init.py", line 398, in <lambda>
    self._add_action_func(lambda rs: rs.outcome.result())
                                     ^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.get_result()
           ^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in get_result
    raise self._exception

  File "/home/scu/.venv/lib/python3.11/site-packages/simcore_sdk/node_ports_common/filemanager.py", line 324, in upload_path
    result = await _upload_path(
             ^^^^^^^^^^^^^^^^^^^

  File "/home/scu/.venv/lib/python3.11/site-packages/simcore_sdk/node_ports_common/filemanager.py", line 406, in _upload_path
    e_tag, upload_links = await _upload_to_s3(
                          ^^^^^^^^^^^^^^^^^^^^

  File "/home/scu/.venv/lib/python3.11/site-packages/simcore_sdk/node_ports_common/filemanager.py", line 456, in _upload_to_s3
    await aws_s3_cli.sync_local_to_s3(

  File "/home/scu/.venv/lib/python3.11/site-packages/simcore_sdk/node_ports_common/aws_s3_cli.py", line 309, in sync_local_to_s3
    await _sync_sources(

  File "/home/scu/.venv/lib/python3.11/site-packages/simcore_sdk/node_ports_common/aws_s3_cli.py", line 222, in _sync_sources
    folder_size = await _get_local_folder_size_and_manage_symlink(Path(source))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/scu/.venv/lib/python3.11/site-packages/simcore_sdk/node_ports_common/aws_s3_cli.py", line 202, in _get_local_folder_size_and_manage_symlink
    total_size += _get_file_size_and_manage_symlink(Path(file_path))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/scu/.venv/lib/python3.11/site-packages/simcore_sdk/node_ports_common/aws_s3_cli.py", line 192, in _get_file_size_and_manage_symlink
    textfile_path.write_text(target_path)

  File "/usr/local/lib/python3.11/pathlib.py", line 1078, in write_text
    with self.open(mode='w', encoding=encoding, errors=errors, newline=newline) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/pathlib.py", line 1044, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by matusdrobuliak66** [comment]
This is connected to AWS S3 CLI functionallity, that we decided we will not support for now. (It was still enabled in master, I have changed it back to RClone now)

**Comment by GitHK** [comment]
@matusdrobuliak66 will this be an issue if the was s3 cli is enabled again? I'd guess so.

**Comment by matusdrobuliak66** [comment]
> @matusdrobuliak66 will this be an issue if the was s3 cli is enabled again? I'd guess so.

Correct, S3 CLI was never enabled outside of Master, and it seems there is at least this issue.

**Comment by sanderegg** [comment]
@matusdrobuliak66 this was fixed? if yes you can close it

**Comment by matusdrobuliak66** [comment]
> @matusdrobuliak66 this was fixed? if yes you can close it

No, this was not fixed because it was caused by the aws cli, which we have decided not to support. Should I close it as "won't fix"?

**Comment by sanderegg** [comment]
well I guess yes

**Comment by matusdrobuliak66** [comment]
As discussed before .. we are not using aws cli.
