### ISSUE TITLE
reconfigure staging stack to use staging S3

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#982]

**Comment by pcrespov** [comment]
@sanderegg I guess this is resolved using #1047

**Comment by sanderegg** [comment]
@pcrespov this is not resolved yet, so please keep it up.
current staging stack uses production S3.

**Comment by sanderegg** [comment]
this is fixed.
